### ISSUE TITLE
Bug: Crashing when compressing multiple files

### ISSUE THREAD

**Issue by phillip-mcnallen-tfs** [notmike101/pack3d#2] opened 2022-05-19 15:52 UTC
This is a bug from Gil:

> The only thing I noticed is that after compressing like 10 - 15 files back to back (just dragging them in compressing, and repeat), the viewport crashes in a weird way where it shows my Windows file explorer preview window. I can try to replicate it and take a screenshot. It only happens after doing many files back to back. Closing it and restarting fixes the issue

**Comment by phillip-mcnallen-tfs** [comment] 2022-05-19 15:59
Not sure the root cause of his crash, though suspect memory related.  Can we take the easy way out by reloading to a fresh instance of the app when a new file is dragged in?  Basically catch the drop event, reload everything to free memory and then pass the drop event after refreshing?  @notmike101

That may be an incorrectly described solution since I'm not familiar with React but hopefully you get the idea.  Is possibly in a simple way?

**Comment by notmike101** [comment] 2022-08-05 04:36
Recreating environment using existing `createEnvironment();` function when model parameter is updated seems to resolve this.

I'm not able to reproduce this issue at this point using code in `dev` branch.

**Comment by notmike101** [comment] 2022-10-13 05:28
Should be resolved in v1.0.4

**Closed as completed** 2022-10-13 05:28 UTC
